# Generated by Django 3.2 on 2022-05-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='like_count',
        ),
    ]
