# Generated by Django 3.2 on 2022-06-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220603_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_rating',
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(blank=True, error_messages={'unique': 'A food with that name already exists.'}, help_text='Food Name', max_length=150, null=True, unique=True, verbose_name='Food Name'),
        ),
    ]
