# Generated by Django 3.2 on 2022-06-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220603_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ingredient Name'),
        ),
    ]
