# Generated by Django 3.2 on 2022-06-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220603_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='food',
            new_name='food_details',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_details',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='food',
            new_name='food_details',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='user_details',
        ),
    ]
