# Generated by Django 3.2 on 2022-06-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220603_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_type',
            field=models.CharField(blank=True, default='Free', max_length=100, null=True),
        ),
    ]
