# Generated by Django 3.2 on 2022-06-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220604_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
