# Generated by Django 3.2 on 2022-06-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_restaurant_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
