# Generated by Django 3.2 on 2022-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220607_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='shipping_charge',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Shipping Charge'),
        ),
    ]
