# Generated by Django 3.2 on 2022-05-20 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_passwordresetid_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetid',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 7, 23, 57, 906395, tzinfo=utc)),
        ),
    ]
