# Generated by Django 3.2 on 2022-05-21 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_auto_20220521_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetid',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 8, 49, 46, 309701, tzinfo=utc)),
        ),
    ]
