# Generated by Django 3.2 on 2022-05-21 08:49

from django.db import migrations, models
import videos.custom_auth.utils


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=videos.custom_auth.utils.get_user_photo_path, width_field='width'),
        ),
    ]
