# Generated by Django 3.2 on 2022-05-23 11:22

from django.db import migrations, models
import videos.custom_auth.utils


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_userphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to=videos.custom_auth.utils.get_category_photo_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to=videos.custom_auth.utils.get_post_photo_path),
        ),
    ]
